### ISSUE TITLE
邮箱可以改为微信推送

### ISSUE THREAD

**Issue by ciring** [LunaticTian/Website-Signed-Gather#2]
邮箱有时候推送会比较慢，微信推送可以解决这个问题
http://sc.ftqq.com/3.version

**Comment by LunaticTian** [comment]
微信推送解决此问题，邮箱推送的快慢主要由发送邮件服务器决定我自己用126的就比较快。微信推送是一个不错的推送选项，我会在后续添加。谢谢！

**Comment by LunaticTian** [comment]
微信推送已增加
