### ISSUE TITLE
运行start.py有报错

### ISSUE THREAD

**Issue by jiutianjuju** [LunaticTian/Website-Signed-Gather#3]
python控制台报错TypeError: an integer is required (got type bytes)
在conf只配置了邮箱和村花的参数
python版本3.8.0

**Comment by LunaticTian** [comment]
村花论坛目前更新了登录代码，需要通过验证google的机器人验证才可登录。此项目关于登录块代码会在后续更新。

**Comment by jiutianjuju** [comment]
了解，后续更新了我再来看看

**Comment by LunaticTian** [comment]
村花部分已修复。
