### ISSUE TITLE
运行报错 求助

### ISSUE THREAD

**Issue by LannYuu** [LunaticTian/Website-Signed-Gather#5]
Douyu.main(cookies=douyuCookie,sum=douyuSum,idList=douyuList,nubList=douyuNum)
AttributeError: module 'Douyu' has no attribute 'main'

**Comment by GeekNOmore** [comment]
碰到了同样的问题，，

**Comment by GeekNOmore** [comment]
在 Douyu.py 的末尾加上这些代码试试
def main(cookies,sum,idList,nubList):
    init(cookie = cookies)
    getYGB()
    mainApi(sum,idList,nubList)
    mail(str(list1),"斗鱼签到情况")

**Comment by LunaticTian** [comment]
如上，douyu模块的入口为mainapi，main并非入口函数。
